---
title: "SharePoint in R"
format: html
execute:
  eval: false
---


```{r}
library('Microsoft365R')

list_sharepoint_sites()

# Delete cached token manually if you get an error about MFA
#unlink("~/.Microsoft365R", recursive = TRUE)

site <- get_sharepoint_site('Fishery & Assessment Data Section Wiki')


# document libraries
site$list_drives()

drv <- site$get_drive()

# Note: I manually put this data into the FADS Wiki SharePoint to illustrate the workflow of FSAR authors uploading data here

# Download file from FADS Wiki SharePoint
drv$download_file("General/FSAR Data/Fraser Pinks/data/generated/benchmarks.csv", overwrite = TRUE)

fr_pk_bms <- readr::read_csv("benchmarks.csv")

```


<!-- # Write this raw data file to Bronze

Just kidding this has to be done in a Databricks Notebook if I want to write a .csv. I can only write delta tables into a database schema from R locally using RJDBC. Which might also work. Using a Databrick notebook would be annoying because I can't read from SharePoint in DataBricks. I could set up pipeline in Azure Data Factory to read from SharePoint, transform, and write to Lakehouse but it seems complicated and maybe overkill.

We could also just read from SharePoint and write to SharePoint silver folder... Makes provisioning access to silver data easier perhaps...

See miro diagram https://miro.com/app/board/uXjVIJyjBWk=/?share_link_id=763283318229

```{r}
library(RJDBC)

jdbc_driver <- JDBC("com.databricks.client.jdbc.Driver", "C:/Users/JOHNSONBRE/DatabricksJDBC42.jar", "")

urlsql <- "jdbc:databricks://adb-553282681420861.1.azuredatabricks.net:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/613056ec98d47d29;"

pat <- Sys.getenv("DATABRICKS_PAT")

connsql <- RJDBC::dbConnect(jdbc_driver, urlsql, "token", pat)
dbGetQuery(connsql, "SELECT 1")

# see what catalog are available
dbGetQuery(connsql, "SHOW CATALOGS")

dbGetQuery(connsql, "SHOW SCHEMAS IN bronze_pacific_prod")

```
# Read data from Bronze

# Transform data to meet SPSR schema

# Write to silver

--> 

