# Provenance and maintenance

dc:creator

prov:wasAttributedTo

dcterms:creator

dcterms:creator "DFO Salmon Team"

dcterms:modified

dcterms:created

skos:note

oboInOwl:consider

oboInOwl:note

skos:scopeNote

skos:editorialNote

rdfs:comment

“This class is provisional, pending review by WG.”
skos:editorialNote "Provisional term - definition to be finalized."@en .

IAO:0000112

IAO:0000112

rdfs:isDefinedBy

rdfs:label

IAO:0000115

rdfs:isDefinedBy   <http://purl.obolibrary.org/obo/bfo.owl>

dcterms:source

oboInOwl:hasDefinitionSource

bfo:0000015 a owl:Class ;

rdfs:label "process"@en ;

IAO:0000115 "An occurrent that has temporal parts."@en ;

rdfs:isDefinedBy <http://purl.obolibrary.org/obo/bfo.owl> .

owl:versionInfo

owl:versionIRI


dcterms:license

dcterms:creator

dcterms:issued

dc:date

rdfs:seeAlso

rdfs:seeAlso   <https://open.canada.ca/data/en/dataset/escapement-survey-

EscapementSurveyEvent

manual-2023> .

dcterms:identifier

dcterms:identifier

skos:notation

:SnorkelSurveyShape  a  sh:NodeShape;  rdfs:label  "Snorkel  survey  data  completeness

shape"@en; sh:targetClass :EscapementSurveyEvent; ...

rdfs:label

rdfs:comment

:StockAssessmentReport a owl:Class ;

rdfs:label "Stock Assessment Report"@en ;

IAO:0000115 "A document presenting the analysis and results of a stock

assessment for a fish population."@en ;

rdfs:isDefinedBy <https://w3id.org/gcdfo/salmon> ;

IAO:0000119 "Term and definition from DFO Stock Assessment Manual

(2021)."@en ;

dcterms:source <https://doi.org/10.1234/DFO-SA-Manual-2021> ;

dcterms:creator "DFO Science Branch, Pacific Region"@en ;

rdfs:seeAlso <https://pacific-salmon-library.example.org/stock-assessment-

reports> .


rdfs:label

IAO:0000115

oboInOwl:hasScope

hasExactSynonym

IAO:0000122

dcterms:license

owl:deprecated true

skos:editorialNote

dc:subject

rdfs:label

oboInOwl:hasExactSynonym

oboInOwl:hasBroadSynonym

oboInOwl:hasNarrowSynonym

oboInOwl:hasRelatedSynonym


oboInOwl:SynonymType

skos:altLabel

skos:hiddenLabel

@en

@en

@fr

@cr

not

escapement"@en

rdfs:label

"Salmon escapement"

"Salmon

GeneticSample

skos:prefLabel   "ESC-001   Sonar   counting"

skos:notation

dcterms:identifier

owl:deprecated true

rdfs:comment "This term is deprecated, use XYZ instead."

oboInOwl:consider

owl:equivalentClass

:EscapementMeasurement a owl:Class ;

rdfs:label "Escapement Measurement"@en ;


IAO:0000115 "A measurement related to salmon escapement (e.g., count of

fish passing a site)."@en ;

oboInOwl:hasExactSynonym "Escapement Count"@en ;

oboInOwl:hasNarrowSynonym "Fence Count"@en ;

# fence count is a specific type of escapement count

...

:SpawningCategory a skos:Concept ;

skos:prefLabel "Spawning observed"@en ;

skos:altLabel "Spawning present"@en ;

skos:altLabel "Spawning seen"@en ;

skos:definition "Indicates that spawning activity was observed in the

survey."@en ;

skos:inScheme :ObservationOutcomeScheme .

:EscapementMeasurement rdfs:label "Mesure d'échappée"@fr .

:EscapementMeasurement IAO:0000115 "Mesure du nombre de poissons échappant

à la pêche et atteignant les frayères."@fr .

@en

oboInOwl:hasExactSynonym

skos:prefLabel


(End of Section 2. Core Conventions. The following sections would continue as per the Table of Contents, applying
