

::: {.content-visible when-profile="english"}

#  National and Regional Resources

This page provides information and resources on national and regional resources related to data stewardship.

## National Resources

- [2023–2026 Data Strategy for the Federal Public Service - Government of Canada](https://www.canada.ca/en/treasury-board-secretariat/corporate/reports/2023-2026-data-strategy.html)
- [Open Government​- Government of Canada](https://open.canada.ca/en) 
- [Be Good Data Stewards - Government of Canada](https://www.canada.ca/en/government/system/digital-government/government-canada-digital-standards/be-good-data-stewards.html)


## Regional Resources 

- [CSAS Pacific](https://www.dfo-mpo.gc.ca/csas-sccs/index-eng.htm)

## Continue exploring the other perspectives:

- [Data Life Cycle](data-life-cycle.qmd)
- [Your Role](your-role.qmd)
- [Data Domain](data-domain.qmd)
- [Recommended Tool Stacks](recommended-tools.qmd)
- [Your Tasks](your-tasks.qmd)

:::

::: {.content-visible when-profile="french"}

# Ressources nationales et régionales

Cette page fournit des informations et des ressources sur les ressources nationales et régionales liées à l'intendance des données.

## Ressources nationales

- [Stratégie de données 2023-2026 pour la fonction publique fédérale - Gouvernement du Canada](https://www.canada.ca/fr/secretariat-conseil-tresor/organisation/rapports/strategie-relative-aux-donnees-2023-2026.html)
- [Gouvernement ouvert - Gouvernement du Canada](https://ouvert.canada.ca/fr) 
- [Soyez de bons gestionnaires de données - Gouvernement du Canada](https://www.canada.ca/fr/gouvernement/systeme/gouvernement-numerique/normes-numeriques-gouvernement-canada/etre-bons-utilisateurs-donnees.html)


## Ressources régionales 

- [SCCS Pacifique](https://www.dfo-mpo.gc.ca/csas-sccs/index-fra.htm)

## Continuez à explorer les autres perspectives :

- [Cycle de vie des données](data-life-cycle.qmd)
- Votre rôle](your-role.qmd)
- Domaine de données](data-domain.qmd)
- [Piles d'outils recommandées](recommended-tools.qmd)
- [Vos tâches](your-tasks.qmd)

:::