#!/usr/bin/env Rscript
# Generates HTML analytics include consumed by Quarto `include-in-header`.
# Defaults to Plausible and supports optional GA4.

dir.create("_includes", showWarnings = FALSE, recursive = TRUE)

provider <- tolower(trimws(Sys.getenv("DSU_ANALYTICS_PROVIDER", "plausible")))
plausible_domain <- trimws(Sys.getenv("PLAUSIBLE_DOMAIN", "dfo-pacific-science.github.io"))
plausible_src <- trimws(Sys.getenv("PLAUSIBLE_SRC", "https://plausible.io/js/script.js"))
ga4_id <- trimws(Sys.getenv("GA4_MEASUREMENT_ID", ""))

if (!(provider %in% c("plausible", "ga4", "none"))) {
  warning(sprintf("Unknown DSU_ANALYTICS_PROVIDER='%s'; falling back to plausible", provider))
  provider <- "plausible"
}

lines <- c("<!-- Generated by scripts/setup_analytics.R -->")

if (provider == "plausible") {
  if (!nzchar(plausible_domain)) {
    warning("PLAUSIBLE_DOMAIN is empty; analytics include will be disabled.")
  } else {
    lines <- c(
      lines,
      sprintf('<script defer data-domain="%s" src="%s"></script>', plausible_domain, plausible_src)
    )
  }
} else if (provider == "ga4") {
  if (!nzchar(ga4_id)) {
    warning("DSU_ANALYTICS_PROVIDER=ga4 but GA4_MEASUREMENT_ID is empty; analytics include will be disabled.")
  } else {
    lines <- c(
      lines,
      sprintf('<script async src="https://www.googletagmanager.com/gtag/js?id=%s"></script>', ga4_id),
      '<script>',
      '  window.dataLayer = window.dataLayer || [];',
      '  function gtag(){dataLayer.push(arguments);}',
      '  gtag("js", new Date());',
      sprintf('  gtag("config", "%s");', ga4_id),
      '</script>'
    )
  }
} else {
  lines <- c(lines, "<!-- Analytics disabled via DSU_ANALYTICS_PROVIDER=none -->")
}

writeLines(lines, "_includes/analytics.html")
cat(sprintf("Wrote _includes/analytics.html (provider=%s)\n", provider))
